FoodStore/Models/GioHang.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace FoodStore.Models
{
    public class GioHang
    {
        private FoodStoreEntities db = new FoodStoreEntities();
        public int productId;
        public string productName;
        public string productImg;
        public double productPrice;
        public int productQuantity;
        public int ShippingFee = 30000;
        public double totalPrice
        {
            get { return productPrice * productQuantity; }
        }

        public GioHang(int id)
        {
            productId = id;
            Product s = db.Products.Single(n => n.ProductId == productId);
            productName = s.ProductName;
            productImg = s.Image;
            productPrice = double.Parse(s.Price.ToString());
            productQuantity = 1;
        }
    }
}

FoodStore/Controllers/GioHangController.cs
using FoodStore.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Mail;
using System.Net;
using System.Web;
using System.Web.Mvc;




namespace FoodStore.Controllers
{
    public class GioHangController : Controller
    {
        // GET: GioHang
        private FoodStoreEntities db = new FoodStoreEntities();



        public List<GioHang> LayGioHang()
        {
            List<GioHang> lstGioHang = Session["GioHang"] as List<GioHang>;
            if (lstGioHang == null)
            {
                lstGioHang = new List<GioHang>();
                Session["GioHang"] = lstGioHang;
            }
            return lstGioHang;
        }



        public JsonResult ThemGioHang(int idproduct)
        {
            List<GioHang> lstGioHang = LayGioHang();
            GioHang sp = lstGioHang.Find(n => n.productId == idproduct);
            if (sp == null)
            {
                sp = new GioHang(idproduct);
                lstGioHang.Add(sp);
            }

            return Json(new { item = sp, success = true }, JsonRequestBehavior.AllowGet);
        }



        private int TongSoLuong()
        {
            int iTongSoLuong = 0;
            List<GioHang> lstGioHang = Session["GioHang"] as List<GioHang>;
            if (lstGioHang != null)
            {
                iTongSoLuong = lstGioHang.Sum(n => n.productQuantity);
            }
            return iTongSoLuong;
        }



        static private double dTongTien = 0;



        public double getTongTien()
        {
            return dTongTien + 30000;
        }
        public double TongTien()
        {
            List<GioHang> lstGioHang = Session["GioHang"] as List<GioHang>;
            if (lstGioHang != null)
            {
                dTongTien = lstGioHang.Sum(n => n.totalPrice);
            }
            return dTongTien;
        }
        public double TongTienHang()
        {
            List<GioHang> lstGioHang = Session["GioHang"] as List<GioHang>;
            if (lstGioHang != null)
            {
                dTongTien = lstGioHang.Sum(n => n.totalPrice);
            }
            return dTongTien;
        }

        public double PhiShip()
        {
            double PhiShip = 30000;
            return PhiShip;
        }





        public ActionResult GioHang()
        {
            List<GioHang> lstGioHang = LayGioHang();
            
            ViewBag.TongSoLuong = TongSoLuong();
            ViewBag.TongTien = TongTien();
            return View(lstGioHang);
        }



        public ActionResult GioHangPartial()
        {
            ViewBag.TongSoLuong = TongSoLuong();
            ViewBag.TongTien = TongTien();
            return PartialView();
        }



        public JsonResult CapNhatGioHang(int id, int quantity)     //truy cập sử dụng Url
        {
            List<GioHang> lstGioHang = LayGioHang();
            GioHang sp = lstGioHang.SingleOrDefault(n => n.productId == id);
            sp.productQuantity = quantity;
            return Json(new { item = sp }, JsonRequestBehavior.AllowGet);
        }



        public JsonResult XoaSPKhoiGioHang(int productId)
        {
            List<GioHang> lstGioHang = LayGioHang();
            GioHang sp = lstGioHang.SingleOrDefault(n => n.productId == productId);
            if (sp != null)
            {
                lstGioHang.RemoveAll(n => n.productId == productId);
                //if (lstGioHang.Count == 0)
                //{
                //    return RedirectToAction("Index", "SACHes");
                //}
            }
            return Json(new { item = sp }, JsonRequestBehavior.AllowGet);
        }




        public ActionResult XoaGioHang()
        {
            List<GioHang> lstGioHang = LayGioHang();
            lstGioHang.Clear();
            return RedirectToAction("Index", "SACHes");
        }



        [HttpGet]
        public ActionResult DatHang()
        {
            if (Session["TaiKhoan"] == null || Session["TaiKhoan"].ToString() == "")
            {
                return Redirect("~/User/DangNhap");
            }
            if (Session["GioHang"] == null)
            {
                return RedirectToAction("Index", "Products");
            }
            List<GioHang> lstGioHang = LayGioHang();
            ViewBag.TongSoLuong = TongSoLuong();
            ViewBag.TongTien = TongTien() + 30000 ;
            ViewBag.PhiShip = PhiShip();
            ViewBag.TongTienHang = TongTienHang();
            return View(lstGioHang);




        }



        [HttpPost]
        public ActionResult DatHang(FormCollection f)
        {
            Order ddh = new Order();
            OrderDetail ct = new OrderDetail();
            Customer kh = (Customer)Session["cmt"];
            List<GioHang> lstGioHang = LayGioHang();
            //.NullReferenceException
            if (kh.CustomerId != null)
            {
                try
                {
                    
                    ddh.CustomerId = kh.CustomerId;
                    
                    ddh.OrderDate = DateTime.Now;
                    ddh.Address = kh.Address;
                    ddh.RecipientPhone = kh.Phone;
               
                    var NgayGiao = String.Format("{0:MM/mm/yyyy}", f["NgayGiao"]);
                    ddh.DeliveryDate = DateTime.Parse(NgayGiao);


                    var giatien = ct.Price ;
                    ddh.OrderPrice = giatien;

                    



                    db.Orders.Add(ddh);
                    db.SaveChanges();
                }
                catch (NullReferenceException e)
                {
                    Console.WriteLine(e);
                }
            }



            foreach (var item in lstGioHang)
            {
                OrderDetail ctdh = new OrderDetail();
                ctdh.OrderId = ddh.OrderId;
                ctdh.ProductId = item.productId;
                ctdh.Quantity = item.productQuantity;
                ctdh.Price = (decimal)item.productPrice;
                db.OrderDetails.Add(ctdh);
            }
            var fromEmail = new MailAddress("chuhaist123@gmail.com", "TDTFood");
            string content = System.IO.File.ReadAllText(Server.MapPath("~/Content/template/neworder.html"));
            string subject = "";
            subject = "Thông Báo";
            content = content.Replace("{{CustomerName}}", kh.CustomerName);
            content = content.Replace("{{Phone}}", kh.Phone);
            content = content.Replace("{{Email}}", kh.Email);
            content = content.Replace("{{Address}}", ddh.Address);
            var lstgiohang = LayGioHang();
            var noidung = "";
            foreach (var item in lstgiohang)
            {
                noidung += item.productName + ", ";
            }
            content = content.Replace("{{Product}}", noidung);
            content = content.Replace("{{Total}}", getTongTien().ToString("N0"));
            var toEmail = new MailAddress(kh.Email);

            var smtp = new SmtpClient
            {
                Host = "smtp.gmail.com",
                Port = 587,
                EnableSsl = true,
                DeliveryMethod = SmtpDeliveryMethod.Network,
                UseDefaultCredentials = true,
                Credentials = new NetworkCredential(fromEmail.Address, "gvnggrtvigbpeihd")
            };
            using (var message = new MailMessage(fromEmail, toEmail)
            {
                Subject = subject,
                Body = content,
                IsBodyHtml = true
            })
                smtp.Send(message);
            db.SaveChanges();

            Session["GioHang"] = null;
            return RedirectToAction("XacNhanDonHang", "GioHang");

           



        }

        public ActionResult ThanhToan()
        {
            return View();
        }

        public ActionResult XacNhanDonHang()
        {
            return View();
        }




    }
}

FoodStore/Controllers/PaypalController.cs
using FoodStore.helper;
using FoodStore.Models;
using PayPal.Api;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FoodStore.Controllers
{
    public class PaypalController : Controller
    {
        // GET: PayPal
        private PayPal.Api.Payment payment;



        GioHangController g = new GioHangController();



        public ActionResult Index()
        {
            return View();
        }



        public ActionResult PaymentWithPaypal()
        {
            APIContext apiContext = helper.Configuration.GetAPIContext();
            try
            {
                string payerId = Request.Params["PayerID"];
                if (string.IsNullOrEmpty(payerId))
                {
                    string baseURI = Request.Url.Scheme + "://" + Request.Url.Authority
                    +
                    "/Paypal/PaymentWithPayPal?";



                    //link trả về khi người dùng hủy thanh toán
                    string failedURI = Request.Url.Scheme + "://" + Request.Url.Authority + "/Paypal/FailureView";


                    var guid = Convert.ToString((new Random()).Next(100000));
                    var createdPayment = this.CreatePayment(apiContext, baseURI + "guid=" + guid, failedURI);
                    var links = createdPayment.links.GetEnumerator();
                    string paypalRedirectUrl = null;
                    while (links.MoveNext())
                    {
                        Links lnk = links.Current;
                        if (lnk.rel.ToLower().Trim().Equals("approval_url"))
                        {
                            paypalRedirectUrl = lnk.href;
                        }
                    }
                    Session.Add(guid, createdPayment.id);
                    return Redirect(paypalRedirectUrl);
                }
                else
                {
                    var guid = Request.Params["guid"];
                    var executedPayment = ExecutePayment(apiContext, payerId, Session[guid] as string);
                    if (executedPayment.state.ToLower() != "approved")
                    {
                        return View("FailureView");
                    }
                }
            }
            catch (Exception ex)
            {
                Logger.Log("Error" + ex.Message);
                return View("FailureView");
            }
            Session["GioHang"] = null;
            return View("SuccessView");


        }


        private Payment CreatePayment(APIContext apiContext, string redirectUrl, string failedUrl)
        {

            var itemList = new ItemList() { items = new List<Item>(), shipping_address = new ShippingAddress() { recipient_name = "Tran Trung Thang", country_code = "VN", city = "Phu Yen", line1 = "An Ninh Dong, Tuy An", postal_code = "700000" } };
            //recipient_name: tên người đặt hàng
            //country_code: code quốc gia, tham khảo thêm tại: https://developer.paypal.com/docs/api/reference/country-codes/
            //city: thành phố shipping
            //line1: địa chỉ giao hàng
            //postal_code: code postal (ví dụ code ở Việt Nam: https://www.google.com/search?q=postal+code+vietnam)
            var payer = new Payer() { payment_method = "paypal" };
            var redirUrls = new RedirectUrls()
            {
                cancel_url = failedUrl, //url cancel
                return_url = redirectUrl //url return
            };

            List<GioHang> listGioHang = Session["GioHang"] as List<GioHang>;

            double tien = Convert.ToDouble(Math.Round((g.getTongTien() / 23000), 0));
            double tongtien = tien + 3;

            foreach (var cart in listGioHang)
            {
                itemList.items.Add(new Item()
                {
                    //Thông tin đơn hàng
                    name = cart.productName,
                    currency = "USD",
                    price = Math.Round(tien, 0).ToString(),
                    quantity = "1",
                    sku = "sku"
                });
            }

            var details = new Details()
            {
                tax = "1",
                shipping = "2",
                subtotal = Math.Round(tien, 0).ToString()
            };

            var amount = new Amount()
            {
                currency = "USD",
                total = Math.Round(tongtien, 0).ToString(),
                details = details
            };
            var transactionList = new List<Transaction>();

            transactionList.Add(new Transaction()
            {
                description = "Transaction description.", //nội dung thanh toán
                invoice_number = DateTime.Now.ToString(), //mã hóa đơn
                amount = amount,
                item_list = itemList
            });
            this.payment = new Payment()
            {
                intent = "sale",
                payer = payer,
                transactions = transactionList,
                redirect_urls = redirUrls
            };
            return this.payment.Create(apiContext);
        }

        private Payment ExecutePayment(APIContext apiContext, string payerId, string paymentId)
        {
            var paymentExecution = new PaymentExecution() { payer_id = payerId };
            this.payment = new Payment() { id = paymentId };
            return this.payment.Execute(apiContext, paymentExecution);
        }

        public ActionResult SuccessView()
        {
            return View();
        }



        public ActionResult FailureView()
        {
            return View();
        }
    }
}

FoodStore/Views/GioHang/DatHang.cshtml
@using FoodStore.Models
@{
    ViewBag.Title = "ĐƠN ĐẶT HÀNG";
    Layout = "~/Views/Shared/_LayoutProduct.cshtml";
}
<style>
    .gh {
        align-items: center;
        display: flex;
        justify-content: center;
        margin-top: 2rem;
    }

    .pd {
        margin-left: 20px;
    }

    .td {
        display: flex;
        align-items: center;
    }

        .td img {
            align-items: center;
            border-radius: 1rem;
        }

    .table-borderless {
        align-items: center;
        margin: 0;
    }

    .name {
        display: block;
        align-items: center;
        margin: 0;
        justify-content: center;
        width: 100%;
    }

    .textgh {
        align-items: center;
    }

    .tx2 {
        font-weight: 500;
        font-size: 15px;
        margin-right: 25px;
        font-weight: bold;
        color: red;
    }

    .tx1 {
        padding: 25px;
        font-weight: 500;
        font-size: 17px;
    }

    .img-gh {
        height: 100px;
        width: 200px;
        object-fit: cover;
    }

    .pay {
        align-items: center;
        display: flex;
        justify-content: center;
    }

        .pay a {
            margin: 20px;
        }
</style>
@{ Customer kh = (Customer)Session["cmt"]; }
@foreach (var item in Model)
{
    <center>
        <div class="container mt-5 mb-5">

            <div class="row gh">
                <div class="col-md-8">

                    <div class="card">
                        <div class="product border-bottom table-responsive">

                            <table class="table table-borderless">

                                <tbody>
                                    <tr>
                                        <td width="20%" class="td">

                                            <img src="~/Content/Images/@item.productImg" class="img-gh">

                                        </td>

                                        <td width="60%" style="vertical-align: inherit">
                                            <div class="name">
                                                <div class="textgh">
                                                    <span class="font-weight-bold tx tx1">Tên món : @item.productName</span>
                                                </div>
                                                <div class="textgh">
                                                    <span class="font-weight-bold tx tx1">Số lượng : @item.productQuantity</span>
                                                </div>

                                            </div>
                                        </td>
                                        <td width="20%" style="vertical-align: inherit">
                                            <div class="text-center">
                                                <span class="font-weight-bold tx2">@item.productPrice đ</span>
                                            </div>
                                        </td>
                                    </tr>
                                </tbody>

                            </table>



                        </div>
                    </div>
                </div>
            </div>
        </div>
    </center>
}

<div class="row gh">

    <div class="col-md-5">

        <table class="table table-borderless">

            <tbody class="totals">

                <tr>
                    <td>
                        <div class="text-left">

                            <span class="text-muted">Tổng tiền hàng: </span>

                        </div>
                    </td>
                    <td>
                        <div class="text-right">
                            <span>@ViewBag.TongTienHang</span>
                        </div>
                    </td>
                </tr>
                <tr>
                    <td>
                        <div class="text-left">

                            <span class="text-muted">Phí giao hàng: </span>

                        </div>
                    </td>
                    <td>
                        <div class="text-right">
                            <span>@ViewBag.PhiShip</span>
                        </div>
                    </td>
                </tr>


                <tr>
                    <td>
                        <div class="text-left">

                            <span class="text-muted">Tổng số lượng: </span>

                        </div>
                    </td>
                    <td>
                        <div class="text-right">
                            <span class="text-success">@ViewBag.TongSoLuong</span>
                        </div>
                    </td>
                </tr>


                <tr class="border-top border-bottom">
                    <td>
                        <div class="text-left">

                            <span class="font-weight-bold">Thành tiền: </span>

                        </div>
                    </td>
                    <td>
                        <div class="text-right">
                            <span class="font-weight-bold">@ViewBag.TongTien đ</span>
                        </div>
                    </td>
                </tr>

            </tbody>

        </table>

    </div>



</div>








<table align="center" style="margin : 0 auto">
    @using (Html.BeginForm())
    {@Html.ValidationSummary(true)
    <tr style="height:40px;"><td>Họ tên khách hàng:</td><td style="font-weight:bold">@kh.CustomerName</td></tr>
    <tr style="height:40px;"><td>Địa chỉ:</td><td style="font-weight:bold">@kh.Address</td></tr>
    <tr style="height:40px;"><td>Điện thoại:</td><td style="font-weight:bold">@kh.Phone</td></tr>
    <tr style="height:40px;">
        <td>Ngày đặt:</td>
        <td style="font-weight:bold">@DateTime.Now.ToShortDateString()</td>
    </tr>
    <tr style="height:40px;">
        <td>Ngày giao:</td>
        <td style="font-weight:bold">
            <input type="date" name="NgayGiao" @ViewData["err"] />
        </td>
    </tr>

    <center>
        <button type="submit" class="btn btn-success">TIẾP TỤC THANH TOÁN</button>
    </center>
}


    </table>



    <h4 style="text-align: center">Thanh toán Online</h4>
    <div class="pay">

        <a href="@Url.Action("Payment","Payment")"><img src="https://vnpay.vn/_nuxt/img/logo-primary.55e9c8c.svg" alt="Alternate Text" width="100px" /></a>
        <a href="@Url.Action("PaymentWithPaypal","Paypal")"><img src="https://www.paypalobjects.com/digitalassets/c/website/logo/full-text/pp_fc_hl.svg" alt="Alternate Text" width="100px" /></a>
        <a href="@Url.Action("Payment","MoMo")"><img src="https://images.viblo.asia/ae87b957-f016-45c0-9c29-34b34a9b3262.png" alt="Alternate Text" width="100px" /></a>
    </div>
    @section GioHang{


        <script src="~/Scripts/Cart.js"></script>
    }

FoodStore/Views/GioHang/GioHang.cshtml
@using FoodStore.Models
@model List<GioHang>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.0/css/all.min.css" integrity="sha512-xh6O/CkQoPOWDdYTDqeRdPCVd1SpvCA9XXcUnZS2FmJNp1coAFzvtCN9BmamE+4aHK8yyUHUSCcJHgXloTyT2A==" crossorigin="anonymous" referrerpolicy="no-referrer" />
@{
    ViewBag.Title = "GioHang";
    Layout = "~/Views/Shared/_LayoutProduct.cshtml";
}

<style>
    .img-gh {
        width: 300px;
        height: 150px;
        object-fit: cover;
        padding: 5px;
        border-radius: 5px;
    }

    .btnBuyNow {
        background-color: orange;
        border: 1px solid blue;
        padding: 8px 16px;
        color: white;
    }

        .btnBuyNow:hover {
            background-color: transparent;
            color: orange
        }
</style>

@if (Model.Count != 0)
{
    <div class="container giohang" style="margin-top : 20px" ;>

        <table class="table">
            <thead>
                <tr>
                    <th>Tên sản phẩm</th>

                    <th>Số lượng</th>
                    <th>Giá tiền</th>
                </tr>
            </thead>
            <tbody class="lstItem">

                @foreach (var item in Model)
                {
                    <tr class="@($"item{ item.productId}" )">
                        <th>
                            <div class="row" style="display : flex; align-items : center; justify-content : flex-start">
                                <img src="~/Content/Images/@item.productImg" class="img-fluid rounded-3 col-xs-12 col-sm-6 col-md-8 img-gh" alt="Book" style="border-radius: 15px; box-shadow: rgba(99, 99, 99, 0.2) 0px 2px 8px 0px;">
                                <div class="col-xs-6 col-md-4">
                                    <p class="mb-2 productName">@item.productName</p>
                                </div>
                            </div>
                        </th>

                        <td class="align-middle" style="vertical-align : inherit">
                            <div class="d-flex flex-row" style="align-items:center; ">
                                <button class="btn btn-link px-2"
                                        onclick="this.parentNode.querySelector('input[type=number]').stepDown()">
                                    @*<i class="fas fa-minus"></i>*@
                                </button>

                                <input min="1" name="txtSoLuong" data-id="@item.productId" value="@item.productQuantity" type="number"
                                       class="form-control form-control-sm quantity" style="width: 50px;" />

                                <button class="btn btn-link px-2"
                                        onclick="this.parentNode.querySelector('input[type=number]').stepUp()">
                                    @*<i class="fas fa-plus"></i>*@
                                </button>
                            </div>
                        </td>
                        <td class="align-middle" style="vertical-align : inherit">
                            <p id="@($"product{ item.productId}" )" data-price="@item.productId" style="font-weight: 500;">@string.Format("{0:#,##0,0}", @item.productPrice) VND</p>
                        </td>
                        <td class="align-middle" style="vertical-align : inherit">
                            <button class="removeItem" data-id="@item.productId"><i class="fas fa-close"></i></button>
                        </td>
                    </tr>
                }
                @*end gio hang*@

            </tbody>
        </table>
        <hr />

        <div style="display : flex; justify-content : flex-end; margin-right : 50px;">
            <div class="d-flex justify-content-between">
                @Html.ActionLink("Xác nhận đơn hàng", "DatHang", "GioHang", new { @class = "btn btn-primary" })
            </div>

        </div>
    </div>
}
else
{
    <div class="container giohang" style="padding : 100px 0; display : flex; flex-direction : column; align-items : center; background-color : #f5f5f5;margin-top : 20px;gap : 30px" ;>
        <img width="100" height="100" src="https://cdn.iconscout.com/icon/free/png-256/bag-1682-1137855.png" alt="Bag Icon - Download in Colored Outline Style" />
        <h4>Giỏ hàng đang trống</h4>
        @Html.ActionLink("Mua ngay", "Index", "Products", null, new { @class = "btnBuyNow" })
    </div>
}
@section GioHang{


    <script src="~/Scripts/Cart.js"></script>
}

FoodStore/Views/GioHang/GioHangPartial.cshtml
<a href="@Url.Action("GioHang","GioHang")">
    <i class="fa fa-shopping-cart"></i><span>Giỏ hàng</span> <div class="qty">@ViewBag.TongSoLuong</div>

</a>

FoodStore/Views/GioHang/XacNhanDonHang.cshtml
@{
    ViewBag.Title = "XacNhanDonHang";
    Layout = "~/Views/Shared/_LayoutProduct.cshtml";
}
<div style="margin-top : 50px; height : 200px; align-items : center; justify-content : center; display : flex;">
    <h4 style="text-align: center">Đặt hàng thành công !</h4>

</div>